import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

        {/* Noise Overlay */}
        <div
          className="
            pointer-events-none
            fixed
            inset-0
            z-[999]
            opacity-[0.03]
            mix-blend-soft-light
          "
          style={{
            backgroundImage: "url('/noise.svg')",
          }}
        />

        {children}

      </body>
    </html>
  );
}